<a href="https://colab.research.google.com/github/tanishajoshi/nlp-fair-redistricting/blob/main/cluster_demographics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import evaltools.data as ed
import us

In [ ]:
# key for sorting clusters
cluster_sort_key = lambda x: x.str.split('-').map(lambda y: list(map(int, y)))

In [ ]:
# read submissions
df_submissions = pd.read_csv('submission_db.csv', usecols=['blocks_2020', 'clusters'], converters={'blocks_2020': eval})
df_clusters = df_submissions.explode('blocks_2020').groupby('clusters').agg(pd.unique).sort_index(key=cluster_sort_key)

In [ ]:
df_clusters

                                                blocks_2020
clusters
1         [295101277003003, 295101256001002, 29183312003...
2         [295101054002020, 295101054001005, 29510105300...
3         [295101256003032, 295101255002018, 29510125600...
4         [291892142002014, 291892160002009, 29189215902...
5         [291892132024014, 291892132033005, 29189215001...
6         [291892107021019, 291892101011004, 29189210704...
7         [292198201073039, 292198201072000, 29219820201...
8         [291892198022017, 291892208011013, 29189219802...
9         [291892188002004, 291892192001017, 29189219602...
10        [291892214233035, 291892214233057, 29099700111...
11        [290997011026000, 292214602001006, 29071801000...
12        [290950085003020, 290950085003015, 29095008500...
13        [290950100011010, 290950100023000, 29095009800...
14        [291650301022009, 291650301021011, 29165030102...
15        [290950153003026, 290950153001017, 29095015300...
16        [290950145032003, 290950145014012, 29095019302...
17        [290950138011027, 290950139163008, 29095018600...
18        [290154607021165, 290154608012188, 29015460802...
19        [290210012001026, 290210012001009, 29021000900...
20        [291950907001078, 291319627021166, 29107090401...
21-1      [290190015083017, 290190015082005, 29019001508...
21-2      [290190013003015, 290190013002016, 29019001300...
22        [291279601001020, 291279601002081, 29127960100...
23        [290019505022039, 290019505012035, 29001950300...
24        [291094704022011, 291094702012059, 29009960202...
25        [290430202072027, 290430202011046, 29043020202...
26        [291679603022051, 291679601023025, 29167960102...
27-1      [290770015002008, 290770015006010, 29077001401...
27-2      [290770005022001, 290770018002037, 29077001800...
28        [292017804002079, 292017804002077, 29201780400...
29        [290318813011011, 290318813021031, 29031881500...
30        [291239602022016, 291239602011041, 29123960201...
31        [291319629011020, 291319629011028, 29131962901...
32        [290270702002134, 290270703011023, 29027070100...
33        [292214602004091, 290718011022026, 29071800502...
34        [290910908022045, 290910908012009, 29091090700...
35        [290910901011037, 290910901021060, 29215480402...

In [ ]:
df_pop = ed.census(us.states.MO)

In [ ]:
# merge population info
df = df_clusters.reset_index().explode('blocks_2020').merge(df_pop, left_on='blocks_2020', right_on='GEOID20', how='left')

In [ ]:
# population totals by cluster
df_summary = df.groupby('clusters').sum(numeric_only=True).sort_index(key=cluster_sort_key)

In [ ]:
df_summary

,TOTPOP20,WHITEPOP20,BLACKPOP20,AMINPOP20,ASIANPOP20,NHPIPOP20,OTHPOP20,WHITEBLACKPOP20,WHITEAMINPOP20,WHITEASIANPOP20,...,BLACKAMINNHPIOTHPOP20,BLACKASIANNHPIOTHPOP20,AMINASIANNHPIOTHPOP20,WHITEBLACKAMINASIANNHPIPOP20,WHITEBLACKAMINASIANOTHPOP20,WHITEBLACKAMINNHPIOTHPOP20,WHITEBLACKASIANNHPIOTHPOP20,WHITEAMINASIANNHPIOTHPOP20,BLACKAMINASIANNHPIOTHPOP20,WHITEBLACKAMINASIANNHPIOTHPOP20
clusters,,,,,,,,,,,,,,,,,,,,,
1,2136175,1489436,402377,5679,74991,770,33930,22979,31486,15036,...,0,0,0,41,38,0,1,2,1,6
2,87898,17744,61466,246,3439,28,1432,928,249,386,...,0,0,0,7,5,0,0,0,0,4
3,193019,108489,55686,677,8008,64,6266,2965,2153,1653,...,0,0,0,1,6,0,0,0,1,3
4,101821,46314,41315,234,6450,30,1795,1183,533,1107,...,0,0,0,3,3,0,0,0,0,0
5,420893,313356,36921,1081,33872,128,8855,4012,4972,4344,...,0,0,0,7,7,0,0,0,0,0
6,162459,94447,51276,441,3104,65,3405,2326,2141,858,...,0,0,0,3,1,0,0,0,0,0
7,505986,429057,23566,1312,11535,272,7480,5415,9694,3429,...,0,0,0,16,11,0,1,0,0,0
8,196185,170041,5999,443,6263,42,1847,1754,2927,1503,...,0,0,0,4,0,0,0,1,0,0
9,439694,355508,31490,849,20585,122,4632,3912,5251,4526,...,0,0,0,7,6,0,0,2,0,0
10,283325,252087,4844,813,5164,86,2328,2237,6488,1817,...,0,0,0,2,1,0,0,1,0,0
11,162924,147753,1255,450,2342,39,1202,939,4045,921,...,0,0,0,1,1,0,0,0,0,0
12,92740,57651,23396,425,2117,54,2196,1250,1225,758,...,1,0,0,4,2,0,0,0,0,0
13,1179245,803761,190119,6930,24918,3630,46207,17706,23820,7849,...,1,2,0,18,23,0,2,1,0,2
14,326385,244756,31174,1852,9448,1687,8696,4617,6699,2770,...,0,0,0,0,3,0,0,1,0,0
15,239570,107441,80212,1729,7396,319,20182,3527,2814,1391,...,1,0,0,6,9,0,1,0,0,0
16,414346,262207,72331,2890,9346,1248,26855,6504,8419,2261,...,0,2,0,8,10,0,2,0,0,0
17,329401,252401,34098,1505,5611,527,7370,4934,7214,2397,...,0,0,0,2,4,0,0,0,0,2
18,162949,146945,2615,950,1032,173,1504,1123,4280,631,...,0,0,0,1,0,0,1,3,0,4
19,117249,100129,4825,548,1528,441,2145,1642,2291,420,...,0,0,0,0,2,0,0,0,0,0
20,528210,435334,36255,2039,10481,943,9320,7403,10535,2941,...,0,0,0,14,17,1,5,2,2,3
21-1,195029,148642,18463,662,7277,531,5500,3599,3178,1486,...,0,0,0,6,4,0,4,0,0,1
21-2,122808,93522,12177,417,5643,80,2210,2363,2029,1085,...,0,0,0,6,3,0,3,1,0,0
22,149173,134611,4346,460,720,41,1236,1589,3106,435,...,0,0,0,6,0,0,1,0,0,0
23,40892,36033,1645,119,795,24,351,352,685,212,...,0,0,0,0,0,0,0,0,0,0
24,129755,105607,1014,2541,1848,1689,6001,627,5463,383,...,0,0,3,1,0,0,1,0,0,0
25,382175,340103,3628,2733,4025,420,6076,2421,11401,1764,...,0,1,0,11,6,0,0,0,0,1
26,80225,71167,1372,560,601,65,1019,805,2400,348,...,0,0,0,1,0,0,0,0,0,1
27-1,348357,294872,10684,2400,6739,455,5809,4755,9987,2366,...,0,1,1,10,0,0,2,0,0,1
27-2,348314,294741,10667,2420,6733,450,5814,4741,9951,2378,...,0,1,1,13,1,0,2,0,0,0
28,34000,21956,9384,100,184,5,722,531,513,42,...,0,0,0,1,0,0,0,0,0,0
29,194691,165724,14928,538,1776,25,1911,1991,3926,562,...,1,0,0,7,3,2,0,0,0,0
30,113706,102556,3530,419,593,24,734,580,2923,266,...,0,0,0,3,0,3,0,0,0,0
31,68988,63614,386,359,298,50,655,310,1698,201,...,0,0,0,5,1,0,0,0,0,0
32,76632,69835,1730,234,277,42,472,570,1903,190,...,0,0,0,0,7,1,0,0,1,0
33,187747,159354,7761,1138,3664,480,2446,1523,4984,1232,...,0,0,0,3,3,1,2,0,0,2
34,64691,59534,278,423,273,26,326,253,2204,169,...,0,0,0,1,0,0,0,0,0,0
35,198957,183073,1065,1174,777,88,1532,878,5880,523,...,0,2,0,11,10,0,0,0,0,1

In [ ]:
df_summary.to_csv('mo_cluster_demographics_p1.csv')